production:
  url: redis://localhost:6379

local: &local
  url: redis://localhost:6379

development: *local
test: *local

# development:
#   adapter: redis
#   url: redis://localhost:6379/1

# test:
#   adapter: async

# production:
#   adapter: redis
#   # url: redis://:3a9f80696b6a0beeae1a8f2a90e44663@redistogo:3a9f80696b6a0beeae1a8f2a90e44663@greeneye.redistogo.com:11648/
#   url: redis://redistogo:6f1bde325547fff26ba749f68fa3cd94@grouper.redistogo.com:11242/
